# Generated by Django 4.0.5 on 2022-06-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='place',
        ),
    ]
