# Generated by Django 4.0.5 on 2022-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_debtor_address_remove_debtor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='email',
            field=models.EmailField(error_messages={'unique': '*Email Id is already taken.'}, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
