# Generated by Django 4.0.5 on 2022-06-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_debtor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passbook', models.BooleanField(default=False)),
                ('bond', models.BooleanField(default=False)),
                ('deed', models.BooleanField(default=False)),
                ('checkleaf', models.BooleanField(default=False)),
                ('additionaldocuments', models.BooleanField(default=False)),
                ('additionaldocumentsname', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(upload_to='mydocs/')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.debtor')),
            ],
        ),
    ]
