# Generated by Django 4.0.5 on 2022-06-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_documents_created_at_documents_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='checkleafcount',
            field=models.BooleanField(default=False),
        ),
    ]
