# Generated by Django 4.0.5 on 2022-06-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_documents_percentage_documents_totalamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidamount', models.CharField(blank=True, max_length=100)),
                ('balanceamount', models.CharField(blank=True, max_length=100)),
                ('pendingdate', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('fineamount', models.CharField(blank=True, max_length=100)),
                ('total', models.CharField(blank=True, max_length=100)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.documents')),
            ],
        ),
    ]
