# Generated by Django 4.0.5 on 2022-06-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_documentamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentamount',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.documentimage'),
        ),
    ]
