# Generated by Django 4.0.5 on 2022-06-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_documentamount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentamount',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.documents'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='debtor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.debtor'),
        ),
    ]
