# Generated by Django 4.0.5 on 2022-06-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_documentamount_amount_alter_documents_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentamount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documentamount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentamount',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.debtor'),
        ),
    ]
