# Generated by Django 4.0.5 on 2022-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_documentamount_created_at_documentamount_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentamount',
            name='balanceamount',
        ),
        migrations.RemoveField(
            model_name='documentamount',
            name='paidamount',
        ),
        migrations.AddField(
            model_name='documents',
            name='balanceamount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documents',
            name='paidamount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
