# Generated by Django 4.0.5 on 2022-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_remove_documentamount_balanceamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='paidamount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
