# Generated by Django 4.0.5 on 2022-06-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_documents_paidamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentamount',
            old_name='amount',
            new_name='debtor',
        ),
        migrations.RenameField(
            model_name='documentamount',
            old_name='fineamount',
            new_name='duedate',
        ),
        migrations.RenameField(
            model_name='documentamount',
            old_name='pendingdate',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='documentamount',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='documentamount',
            name='total',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='balanceamount',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='paidamount',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='totalamount',
        ),
        migrations.AddField(
            model_name='documentamount',
            name='balanceamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documentamount',
            name='paidamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documentamount',
            name='totalamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='IntrestAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingdate', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('fineamount', models.CharField(blank=True, max_length=100)),
                ('total', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.debtor')),
            ],
        ),
    ]
