# Generated by Django 4.0.5 on 2022-06-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_remove_documents_balanceamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='percentage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documents',
            name='totalamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='documentamount',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.documents'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.debtor'),
        ),
        migrations.AlterField(
            model_name='intrestamount',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.documents'),
        ),
    ]
