# Generated by Django 4.0.5 on 2022-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_documents_percentage_documents_totalamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='docno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
