# Generated by Django 4.0.5 on 2022-06-23 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_documents_docno'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentamount',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 12, 1, 22, 196722)),
        ),
    ]
