# Generated by Django 4.0.5 on 2022-06-23 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_documentamount_paid_alter_documents_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentamount',
            name='paid',
        ),
        migrations.AddField(
            model_name='intrestamount',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 12, 3, 16, 621905)),
        ),
    ]
