# Generated by Django 4.0.5 on 2022-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_remove_documentamount_paid_intrestamount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
