# Generated by Django 4.0.5 on 2022-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_alter_documents_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrestamount',
            name='intrestamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
