# Generated by Django 4.0.5 on 2022-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_rename_total_intrestamount_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentamount',
            name='fineamount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentamount',
            name='pendingdate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentamount',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
