# Generated by Django 4.0.5 on 2022-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_documentamount_fineamount_documentamount_pendingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentamount',
            name='duedate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentamount',
            name='fineamount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentamount',
            name='pendingdate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentamount',
            name='percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentamount',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentamount',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
