# Generated by Django 4.0.5 on 2022-06-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_alter_documents_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentamount',
            name='duedate',
        ),
        migrations.AddField(
            model_name='documents',
            name='duedate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
