# Generated by Django 4.0.5 on 2022-06-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_remove_documentamount_duedate_documents_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='balanceamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='fineamount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documents',
            name='intamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='pendingdate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documents',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documents',
            name='result',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documents',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
