# Generated by Django 4.0.5 on 2022-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_documents_balanceamount_documents_fineamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentamount',
            name='duedate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intrestamount',
            name='duedate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
