# Generated by Django 4.0.5 on 2022-06-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_alter_documents_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='paidamount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
