# Generated by Django 4.0.5 on 2022-06-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_debtor_fullname_documents_paidamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidUnpaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('duedate', models.DateTimeField(null=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.documents')),
            ],
        ),
    ]
