# Generated by Django 4.0.5 on 2022-07-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_paidunpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='checkleafcount',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
